example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml 
from wishlist.views import show_json 
from wishlist.views import show_json_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user, show_wishlist_ajax

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name= 'show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='ajax'),
    # path('ajax/submit', create_wishlist, name='create_wishlist'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()

wishlist/forms.py
from django import forms

from .models import *

class WishlistForm(forms.ModelForm):
    title= forms.CharField(widget= forms.TextInput())
    harga = forms.IntegerField(widget= forms.TextInput())
    description= forms.CharField(widget=forms.Textarea(attrs={'style': 'width: 15em;'}))

    class Meta:
        model = BarangWishlist
        fields = ('title', 'harga', 'description')

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from calendar import day_abbr
from json import JSONDecodeError
from sqlite3 import DatabaseError
from django.shortcuts import render
from wishlist.forms import WishlistForm
from wishlist.models import BarangWishlist
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.models import User

data_barang_wishlist = BarangWishlist.objects.all()

newForm = WishlistForm()



@login_required(login_url='/wishlist/login/')

# Create your views here.
def show_wishlist(request):
    context = {
    'list_barang': data_barang_wishlist,
    'nama': 'Carlene Annabel',
    'last_login': request.COOKIES['last_login'],
   }
    return render(request, "wishlist.html", context)

def show_wishlist_ajax(request):
    context = {
        'nama': 'Carlene Annabel',
        'last_login': request.COOKIES['last_login'],
        'form': newForm
    }
    return render(request, 'wishlist_ajax.html', context)

def show_xml(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request,id):
    data = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
           login(request, user) # melakukan login terlebih dahulu
           response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
           response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
           return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

# def create_wishlist(request):
#     user_name = User.objects.get(username=request.user)    
#     form = WishlistForm()
#     new_task = None
#     if request.method == 'POST':
#         form = WishlistForm(request.POST)
#         if form.is_valid():
#             new_task = form.save(commit=False)
#             new_task.user = request.user
#             new_task.save()
#         return HttpResponseRedirect(reverse("wishlist:show_wishlist"))
#     context = {'form': form}
#     return render(request, 'wishlist_form.html', context)

# def create_wishlist(request):
#     if request.method == 'POST':
#         nama_barang = request.POST.get('nama_barang')
#         harga_barang = request.POST.get('harga_barang')
#         deskripsi = request.POST.get('deskripsi')
#         BarangWishlist.objects.create()
#         wishlist = BarangWishlist.objects.create(nama_barang=nama_barang,deskripsi=deskripsi,harga_barang=harga_barang)
#         response = HttpResponseRedirect(reverse("wishlist:show_wishlist_ajax")) 
#         return response
#     return render(request, 'wishlist_ajax.html', wishlist)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <!-- INCLUDING JQUERY-->
  <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  
  {% block meta %}
  {% endblock meta %}

  <style>
    body {
      background-color: #F3EBF6;
      font-family: 'Ubuntu', sans-serif;
      align-center;
      flex;
      justify:center;
    }

    .login {
      background-color: #FFFFFF;
      width: 400px;
      height: 400px;
      margin: 7em auto;
      border-radius: 1.5em;
      box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);
      text-align:center
      {% comment %} display:flex
      align-item:center
      justify-content:center {% endcomment %}
    }

    .register {
      background-color: #FFFFFF;
      width: 700px;
      height: 600px;
      margin: 10em auto;
      border-radius: 1.5em;
      box-shadow: 0px 11px 35px 2px rgba(0, 0, 0, 0.14);
      text-align:center
   
    }

    .sign {
      padding-top: 40px;
      color: #8C55AA;
      font-family: 'Ubuntu', sans-serif;
      font-weight: bold;
      font-size: 23px;
    }

    .un {
      width: 76%;
      color: rgb(38, 50, 56);
      font-weight: 700;
      font-size: 14px;
      letter-spacing: 1px;
      background: rgba(136, 126, 126, 0.04);
      padding: 10px 20px;
      border: none;
      border-radius: 20px;
      outline: none;
      box-sizing: border-box;
      border: 2px solid rgba(0, 0, 0, 0.02);
      margin-bottom: 50px;
      margin-left: 80px;
      text-align: center;
      margin-bottom: 27px;
      font-family: 'Ubuntu', sans-serif;
      }

      .pass {
        width: 76%;
        color: rgb(38, 50, 56);
        font-weight: 700;
        font-size: 14px;
        letter-spacing: 1px;
        background: rgba(136, 126, 126, 0.04);
        padding: 10px 20px;
        border: none;
        border-radius: 20px;
        outline: none;
        box-sizing: border-box;
        border: 2px solid rgba(0, 0, 0, 0.02);
        margin-bottom: 50px;
        margin-left: 80px;
        text-align: center;
        margin-bottom: 27px;
        font-family: 'Ubuntu', sans-serif;
        }

        .un:focus, .pass:focus {
          border: 2px solid rgba(0, 0, 0, 0.18) !important;
     
        }

        .btn{
            cursor: pointer;
            border-radius: 5em;
            color: #fff;
            background: linear-gradient(to right, #ec6f66 , #f3a183);
           
        }

        .listtable {
          border-collapse: collapse;
          margin: 25px 0;
          font-size: 0.9em;
          font-family: sans-serif;
          min-width: 400px;
          box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
          text-align: center;
          margin-left: auto;
          margin-right: auto;
        }

        .listtable thead tr {
          background-color: #8cbcb2;
          color: #f3a183;
          text-align: left;
        }

        .listtable th, td{
          padding: 12px 15px;
        }

        .listtable tbody tr {
          border-bottom: 1px solid #f3a183;
          }
      
          .listtable tbody tr:last-of-type {
              border-bottom: 2px solid #ec6f66;
          }
      
          .container-fluid {
            background-color: #ec6f66
          }
          .collapse navbar-collapse {
            background-color: #ec6f66

          }
        
      .form-wishlist{
        display: inline-block;
      }
        
      {% comment %} .wishlist-container {
        max-width: 900px;
        margin: auto;
        background-color: #fff;
        -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
        box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
        text-align: center;
      } {% endcomment %}

 



  </style>
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    {% comment %} <h1>Login</h1> {% endcomment %}
    <p class="sign" align="center">Login</p>
    <form method="POST" action="" class="form1">
        {% csrf_token %}
        <table>
            <tr>
                {% comment %} <td>Username: </td> {% endcomment %}
                <td><input type="text" align="center" name="username" placeholder="Username" class="un"></td>
            </tr>
                    
            <tr>
                {% comment %} <td>Password: </td> {% endcomment %}
                <td><input type="password" align="center" name="password" placeholder="Password" class="pass"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn" align="center" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "register">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}

{% block content %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{nama}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<div class="wishlist-container">
  <table class="listtable">
      <tr>
      <th>Nama Barang</th>
      <th>Harga Barang</th>
      <th>Deskripsi</th>
      </tr>
      {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
      {% for barang in list_barang %}
      <tr>
          <th>{{barang.nama_barang}}</th>
          <th>{{barang.harga_barang}}</th>
          <th>{{barang.deskripsi}}</th>
      </tr>
      {% endfor %}
  </table>
</div>

<h5>Sesi terakhir login: {{ last_login }}</h5>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>


{% endblock content %}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}

{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{nama}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'wishlist:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<div class="wishlist-container flex justify-center">
    <table class="listtable" id='listtable'>
        <tr>
        <th>Nama Barang</th>
        <th>Harga Barang</th>
        <th>Deskripsi</th>
        </tr>
        {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
        {% comment %} {% for barang in list_barang %}
        <tr>
            <th>{{barang.nama_barang}}</th>
            <th>{{barang.harga_barang}}</th>
            <th>{{barang.deskripsi}}</th>
        </tr>
        {% endfor %} {% endcomment %}
        
    </table>
    <div class="form-wishlist">
        <form method="POST" action="" id="newForm">
            {% csrf_token %}
            {% comment %} <table>
                {{form.as_p}}
                <tr>  
                    <td></td>
                    <td><input class="btn" type="submit" name="submit" value="Create Task"/></td>
                </tr>  
                <tr>
                    <td></td>
                    <td><input class="btn" type="button" value="Go back!" onclick="history.back()"></td>
                </tr>
            </table> {% endcomment %}
            {%for fm in form%}
                <div class="form-apa">
                    <label>{{fm.label}}</label>
                    <p>{{fm}}</p>
                </div>
            {%endfor%}
            <div class="tombol flex-col ">
                <input class="btn" type="submit" name="submit" value="Add" id="submit_btn"/>
                <input class="btn" type="button" value="Go back!" onclick="history.back()">
            </div>
        </form>
        
    </div>
  
</div>
<script>
    var list1 = [];
    var list2 = [];
    var list3 = [];
    var n = 1;
    var x=0;

    async function AddRow(){
        var AddRow = document.getElementById('listtable');
        var NewRow = AddRow.insertRow(n);
        var wishlist = '';
        list1[x] = document.getElementById('nama_barang').value;
        list2[x] = document.getElementById('harga_barang').value;
        list3[x] = document.getElementById('deskripsi').value;

        wishlist+= '<tr>';
        wishlist += '<th>' + list1[x] + '</th>';
        wishlist += '<th>' + list2[x] + '</th>';
        wishlist += '<th>' + list3[x] + '</th>';
        wishlist += '</tr>';

        $('#listtable').append(wishlist)

        n++;
        x++;
    }
    $(document).ready(function(){
        $.getJSON("{% url 'wishlist:show_json'%}",function(data){
                    var wishlist = '';
                    $.each(data, function(key,value){
                        wishlist+= '<tr>';
                        wishlist += '<th>' + value.fields.nama_barang + '</th>';
                        wishlist += '<th>' + value.fields.harga_barang + '</th>';
                        wishlist += '<th>' + value.fields.deskripsi + '</th>';
                        wishlist += '</tr>';
                    });
                    $('#listtable').append(wishlist);

          });
          $("#submit_btn").click(function(){
            {% comment %} $.post("http://localhost:8000/wishlist/ajax/submit", {nama_barang: $("#nama_barang").val(),harga_barang:parseInt($("#harga_barang").val()),deskripsi:$("#deskripsi").val()} ) {% endcomment %}
            $.post("http://localhost:8000/wishlist/ajax/submit",AddRow() )
              })
    });

    

    
</script>

<h5>Sesi terakhir login: {{ last_login }}</h5>

<button><a href="{% url 'wishlist:logout' %}">Logout</a></button>




{% endblock content %}